name: PROFLEXO FULL STACK - CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to VDS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_KEY }}
        script: |
          cd ~/proflexo/web
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart proflexo.service
